table 01_SalesMeasures
	lineageTag: 755c9e95-075f-439a-b2c2-737afcf807a2

	/// Total sales revenue
	measure 'Potential Revenue' = SUM(fact_sales[price_total])
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: b234826c-fd73-4b22-9a8a-378ed0bdb998

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Total Quantity' = CALCULATE(SUM(fact_sales[product_qty]), fact_sales[order_state] = "done")
		formatString: #,##0.00
		displayFolder: Product
		lineageTag: 0c942e07-8b6a-480b-a1b1-55dc48912e79

		changedProperty = IsHidden

	/// Count of total orders
	measure 'Total Orders' = DISTINCTCOUNT(fact_sales[order_id])
		formatString: #,##0
		lineageTag: 7430c822-7a69-437d-beca-6150d9b24db5

		changedProperty = IsHidden

	/// Average sales per order
	measure 'Average Order Value' = DIVIDE([Realized Revenue], [Completed Orders])
		formatString: #,##0 "EGP"
		lineageTag: 7775b77d-841b-4f94-b6d7-4f4c50c6885a

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Number of unique customers
	measure 'Customer Count' = DISTINCTCOUNT(fact_sales[customer_id])
		formatString: #,##0
		displayFolder: Customer
		lineageTag: 919830bc-d179-4ac5-914b-906345fb1faf

		changedProperty = IsHidden

	measure 'Product Count' = DISTINCTCOUNT(fact_sales[product_id])
		formatString: #,##0
		displayFolder: Product
		lineageTag: 30f6950c-f653-429d-9c57-07c6ada977fc

		changedProperty = IsHidden

	/// Total discount amount
	measure 'Total Discount' = SUM(fact_sales[discount])
		formatString: #,##0 "EGP"
		lineageTag: 1c1a15b3-bd31-4746-a509-fdaa3fc5ad06

		changedProperty = IsHidden

	/// Total tax amount
	measure 'Total Tax' = SUM(fact_sales[price_tax])
		formatString: #,##0 "EGP"
		lineageTag: bae93043-9567-4b3d-a50c-8d5dd6f2291a

		changedProperty = IsHidden

	/// Net revenue (after discount)
	measure 'Realized Revenue' =
			CALCULATE (
			    SUM ( fact_sales[net_revenue] ),
			    fact_sales[order_state] = "done"
			)
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: 3b9f850c-4f5e-41c1-aa05-abcdb441497f

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Average quantity per order
	measure 'Average Quantity per Order' = DIVIDE([Total Quantity], [Completed Orders])
		formatString: #,##0.00
		displayFolder: Product
		lineageTag: 49b9ccbe-c8e2-49c4-aff1-97da9ed0fc36

		changedProperty = IsHidden

	/// Average unit price
	measure 'Average Unit Price' = SUM(fact_sales[price_unit]) / SUMX(DISTINCT(fact_sales[product_id]), DISTINCTCOUNT(fact_sales[product_id]))
		formatString: #,##0 "EGP"
		displayFolder: Product
		lineageTag: f867108f-d357-4148-9053-33ba3deaca4c

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Month-to-date sales
	measure 'MTD Sales' = TOTALMTD([Potential Revenue], dim_date[full_date])
		formatString: #,##0 "EGP"
		displayFolder: RFM
		lineageTag: 2f957428-2dcd-449f-a2d5-c95fa00e4c43

		changedProperty = IsHidden

	/// Previous month sales
	measure 'Previous Month Sales' = CALCULATE([Realized Revenue], DATEADD(dim_date[full_date], -1, MONTH))
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: 715bf64c-d7e4-482d-88fa-be8ac72607a0

		changedProperty = IsHidden

	/// Month-over-month growth %
	measure 'MoM Growth %' = DIVIDE(([Realized Revenue] - [Previous Month Sales]), [Previous Month Sales])
		formatString: 0.00%
		displayFolder: Revenue
		lineageTag: 96b4348c-8f0a-4c9b-88cb-9d36281f94e6

		changedProperty = IsHidden

	/// Previous year sales
	measure 'Previous Year Sales' = CALCULATE([Realized Revenue], DATEADD(dim_date[full_date], -1, YEAR))
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: 91307602-140c-4712-a3d1-32365bbeb7f3

		changedProperty = IsHidden

	/// Average order size
	measure 'Average Order Size' = DIVIDE([Total Quantity], [Total Orders])
		formatString: #,##0 "EGP"
		lineageTag: 26c1670f-a35f-451f-9fea-16eebc0d3a22

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isCustom":true}

	/// Completed orders
	measure 'Completed Orders' =
			
			CALCULATE (
			    DISTINCTCOUNT ( fact_sales[order_id] ),
			    fact_sales[order_state] = "done"
			)
		formatString: #,##0
		lineageTag: 635f89ab-6567-4efd-9ea3-12b183d76543

		changedProperty = IsHidden

	measure 'Confirmed Revenue' =
			
			CALCULATE (
			    SUM ( fact_sales[gross_revenue] ),
			    fact_sales[order_state] IN { "sale", "done" }
			)
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: 35e33486-63e1-49df-be19-17c0d7565575

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Lost Revenue' =
			
			CALCULATE (
			    SUM ( fact_sales[price_total] ),
			    fact_sales[order_state] = "cancel"
			)
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: 5d5bb965-70ab-4ada-93f9-7df34b704aeb

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Cancelled Orders' =
			CALCULATE (
			    DISTINCTCOUNT ( fact_sales[order_id] ),
			    fact_sales[order_state] = "cancel"
			)
		formatString: 0
		lineageTag: 625e95b2-b28b-445c-be6f-9fcdf90ce724

	measure 'Pending Orders Value' =
			CALCULATE (
			    SUM ( fact_sales[price_total] ),
			    fact_sales[order_state] = "draft"
			)
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: c2c35643-54fe-4996-a901-2c0829c535fd

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Opportunity Value' =
			CALCULATE (
			    SUM ( fact_sales[price_total] ),
			    fact_sales[order_state] = "sent"
			)
		formatString: #,##0 "EGP"
		displayFolder: Revenue
		lineageTag: 36d27770-e5e0-4f55-ad44-36af9bad4d88

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Lost Rate %' = DIVIDE( [Lost Revenue] ,[Opportunity Value] , 0)
		displayFolder: Revenue
		lineageTag: 209dcbf6-e38a-4528-a7aa-29f17fa1fcf5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Conversion Rate %' = DIVIDE( [Realized Revenue] , ([Confirmed Revenue]+[Opportunity Value]) , 0)
		displayFolder: Revenue
		lineageTag: 4173ebf8-0e6d-4f37-9f8f-724c3b38e9d5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Product Revenue' = CALCULATE(SUM(fact_sales[net_revenue]), fact_sales[order_state] = "done")
		formatString: #,##0 "EGP"
		displayFolder: Product
		lineageTag: 778aec98-f040-4b24-aae9-c1e335c8f36c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Contribution %' =
			DIVIDE(
			    [Product Revenue],
			    [Total Revenue]
			)
		displayFolder: Product
		lineageTag: d8b1c9e5-5ec3-45ee-8221-058da8241ae7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue' =
			
			CALCULATE(
			    [Product Revenue],
			    ALL(dim_product)
			)
		formatString: #,##0 "EGP"
		lineageTag: 03966c4e-f283-48fe-a6b2-3633aeaa6f30

	measure 'Product Rank' =
			
			RANKX(
			    ALL(dim_product[product_name]),
			    [Product Revenue],
			    ,
			    DESC
			)
		formatString: 0
		displayFolder: Product
		lineageTag: b05c1f9d-4435-470e-9b31-12ae5f727eb7

	measure 'Cumulative Revenue' =
			
			VAR CurrentRank = [Product Rank]
			RETURN
			CALCULATE(
			    [Product Revenue],
			    FILTER(
			        ALL(dim_product[product_name]),
			        [Product Rank] <= CurrentRank
			    )
			)
		formatString: #,##0 "EGP"
		displayFolder: Product
		lineageTag: f293886c-0497-4b60-b9f4-c7b995b7cce0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Cumulative %' =
			
			DIVIDE([Cumulative Revenue], [Total Revenue])
		displayFolder: Product
		lineageTag: 0700983a-127e-4be1-9369-0b40f04ea010

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Customer Value' = DIVIDE( [Realized Revenue],DISTINCTCOUNT(fact_sales[customer_id]),0)
		formatString: #,##0 "EGP"
		lineageTag: 93ebf884-9145-4a87-beab-6341ec95f332

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'YoY Net Growth %' = DIVIDE(([Realized Revenue] - [Previous Year Sales]), [Previous Year Sales])
		displayFolder: Revenue
		lineageTag: 8ca8e477-46df-4058-acd6-de24ff6f5b57

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Last Purchase Date' = MAX(fact_sales[order_date])
		formatString: General Date
		displayFolder: RFM
		lineageTag: 50703535-6397-4cf7-9f1c-10542e669d5b

	measure 'Recency Days' =
			DATEDIFF(
			    [Last Purchase Date],
			    TODAY(),
			    DAY
			)
		formatString: 0
		displayFolder: RFM
		lineageTag: 1c73a832-6720-490c-9fd1-a80b349273b5

	measure Frequency = DISTINCTCOUNT(fact_sales[order_id])
		formatString: 0
		displayFolder: RFM
		lineageTag: b28b9005-d672-4443-9c06-f9ab0829da23

	measure Monetary = SUM(fact_sales[net_revenue])
		formatString: #,##0 "EGP"
		displayFolder: RFM
		lineageTag: 6932671b-8c07-45e6-9ff1-f08b634b5ad5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Retention Rate' =
			
			VAR PreviousCustomers =
			    CALCULATETABLE(
			        VALUES(fact_sales[customer_id]),
			        DATEADD(fact_sales[order_date], -1, YEAR)
			    )
			
			VAR CurrentCustomers =
			    VALUES(fact_sales[customer_id])
			
			VAR RetainedCustomers =
			    INTERSECT(
			        PreviousCustomers,
			        CurrentCustomers
			    )
			
			RETURN
			DIVIDE(
			    COUNTROWS(RetainedCustomers),
			    COUNTROWS(PreviousCustomers)
			)
		displayFolder: Customer
		lineageTag: 45a47d68-bfd3-49f9-9fb5-4c03935e2805

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Purchase Frequency' =
			
			DIVIDE(
			    [Completed Orders],
			    DISTINCTCOUNT(fact_sales[customer_id])
			)
		displayFolder: Customer
		lineageTag: f6c1cb2f-ebb2-4719-9c00-2efe2b4ee9eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Customer Lifespan' = 3
		formatString: 0
		displayFolder: Customer
		lineageTag: a233cd73-d9b1-4555-9de9-92744f888895

	measure CLV =
			
			[Average Order Value] *
			[Purchase Frequency] *
			[Customer Lifespan]
		formatString: #,##0 "EGP"
		displayFolder: Customer
		lineageTag: 94354605-f29d-4782-8b96-32f001e23e46

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure PreviousCustomers =
			
			CALCULATETABLE(
			    VALUES(fact_sales[customer_id]),
			    SAMEPERIODLASTYEAR(dim_date[full_date])
			)
		formatString: 0
		displayFolder: Customer
		lineageTag: 5145479d-5cd9-4dba-966d-7ea37f43954c

	measure 'Repeat Customers' =
			
			COUNTROWS(
			    FILTER(
			        VALUES(fact_sales[customer_id]),
			        CALCULATE(
			            DISTINCTCOUNT(fact_sales[order_id]),
			            fact_sales[order_state] = "done"
			        ) > 1
			    )
			)
		formatString: 0
		displayFolder: Customer
		lineageTag: 17a22343-f20f-4d38-94fa-8137625d5aec

	measure 'New Customers' =
			
			COUNTROWS(
			    FILTER(
			        VALUES(fact_sales[customer_id]),
			        CALCULATE(
			            DISTINCTCOUNT(fact_sales[order_id]),
			            fact_sales[order_state] = "done"
			        ) = 1
			    )
			)
		formatString: 0
		displayFolder: Customer
		lineageTag: 87502626-790f-4845-b6ae-65c85be978d7

	measure 'Total Quantity Sold' = CALCULATE(SUM(fact_sales[product_qty]),fact_sales[order_state] = "done")
		lineageTag: 7ad66a3a-a4f1-46d0-8d04-90f000d2ceaa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Movement Qty' = SUM(fact_inventory_movement[moved_qty])
		lineageTag: 8dca6296-13c7-43eb-9e7c-1612e5c37c36

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 01_SalesMeasures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

